# yml template to dockerise a node.js app
version: '3'
services: 
    estimationtool: 
        container_name: estimationtool
        build: .
        image: maschroder/estimationtool
        ports: 
            - '3000:3000'

        