# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: frontend
        build: .
        image: maxi/frontend
        ports: 
            - '3000:3000'
          
    backend:
        depends_on: [frontend]
        container_name: backend 
        image: maxi/backend
        ports:
            - "4000:4000"
        