# yml template to dockerise a node.js app
version: '3'
services: 
    appservice: 
        container_name: frontend
        build: .
        #image: 
        ports: 
            - '3000:3000'
        depends_on: 
            - backend   
    backend:
        container_name: backend 
        image: 
        ports:
            - 
        volumes:
            - 