# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: frontend
        build: .
        #image: imagename
        ports: 
            - '3000:3000'
          
    backend:
        container_name: backend 
        #image: imagename
        ports:
            - "8080:8080"
        