# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: frontend
        build: .
        image: 2001310/frontend
        ports: 
            - '3000:3000'
          
    backend:
        container_name: backend 
        image: 2001310/backend
        ports:
            - "4000:4000"
        volumes:
            - database:/app/database
            
volumes:
    database:
        