# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: atlantgisfrontend
        image: luening/geosoft2-frontend
        ports: 
            - '3000:3000'
        volumes:
            - database:/usr/src/app/database
          
    backend:
        container_name: atlantgisbackend 
        image: luening/geosoft2-backend
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - database:/usr/src/app/database

volumes:
    database:
    