# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: atlantigsfrontend
        build: .
        image: 2001310/frontend
        ports: 
            - '3000:3000'
          
    backend:
        container_name: pumberbackend 
        build: .
        image: maschroder/plumberbackend
        restart: always
        ports:
            - "4000:4000"
    
    