# yml template to dockerise a node.js app
version: '3'
services: 
    frontend: 
        container_name: atlantigsfrontend
        build: .
        image: 2001310/frontend

        ports: 
            - '3000:3000'
        volumes:
            - database:/app/database
          
    backend:
        container_name: backend 
        build: .
        image: 2001310/backend
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - database:/app/database

volumes:
    database:
    